### ISSUE TITLE
Feedback Request: NTW 02 Network devices

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#13]
**Feedback Request Network devices**
Permalink to file: [Network devices](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%202%20Networking/NTW-02%20Network%20Devices.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? **Yes but could be more extensive**
- Is the summary written in own words? **Yes**
- Is there crucial information missing in the summary? **See above**
- Is the description clear enough? **Yes**

**Key Terminology**
- Are there missing key terms? **Maybe you can also add the devices described at the result at this point**
- Are the key terms explained well? **Yes**

**Sources**
- Are the sources mentioned? **Yes**
- Are the mentioned sources correct? **Yes**

**Excercise**
(Where applicable)
- Is the result correct? **Yes**
- Are the experienced problems and solutions described well? **Yes**

**Comment by archana-sekarr** [comment]
**Summary**
- Does the summary describe the subject matter fully? I see you have explained the concept in results but the summary could have been elaborated.
- Is the summary written in own words? yes
- Is there crucial information missing in the summary? yes
- Is the description clear enough? most of the information is found in results,

**Key Terminology**
- Are there missing key terms? no
- Are the key terms explained well? yes

**Sources**
- Are the sources mentioned? yes
- Are the mentioned sources correct? yes

**Excercise**
(Where applicable)
- Is the result correct? yes
- Are the experienced problems and solutions described well? yes

**Comment by Tjomba1996** [comment]
Very clear, nothing to add
