### ISSUE TITLE
Feedback Request: NTW 03 Protocols

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#14]
**Feedback Request NTW 03 Protocols**
Permalink to file: [NTW 03 Protocols](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%202%20Networking/NTW-03%20Protocols.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? **Yes**
- Is the summary written in own words? **Yes**
- Is there crucial information missing in the summary? **No**
- Is the description clear enough? **Yes**

**Key Terminology**
- Are there missing key terms? **No**
- Are the key terms explained well? **Yes**

**Sources**
- Are the sources mentioned? **Yes**
- Are the mentioned sources correct? **Yes**

**Excercise**
(Where applicable)
- Is the result correct? **Yes**
- Are the experienced problems and solutions described well? **Yes**

**Comment by Tjomba1996** [comment]
Maybe use some more syntax for the layout to make it clearer.
