### ISSUE TITLE
Feedback Request: NTW 6 Subnetting

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#19]
**Feedback Request NTW 6 Subnetting]**
Permalink to file: [NTW 6 Subnetting](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%202%20Networking/NTW-06%20Subnetting.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
In the results, the IP of the sub has one "0" too many.

**Comment by archana-sekarr** [comment]
> In the results, the IP of the sub has one "0" too many.

Yes, Other than this everything else is explained very well.
