### ISSUE TITLE
Feedback Request: Git en Github

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#2]
**Feedback Request Git en Github**
Permalink to file: [Git en github](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/aaa0e6319f8bd0e7d92fb731289a67f3ff78a4d2/01_Fundamentals_1/%20Git%20en%20Github.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by sasudi90** [comment]
- Samenvatting is volledig 
- Key terminology is in eigen woorden en compleet.  
- Vergeet je exercise niet in de uitwerking te zetten
- Resultaat is goed

**Comment by yismailmo** [comment]
**Summary**
- Does the summary describe the subject matter fully?yes
- Is the summary written in own words?yes
- Is there crucial information missing in the summary?no
- Is the description clear enough?yes

**Key Terminology**
- Are there missing key terms?no
- Are the key terms explained well?yes

**Sources**
- Are the sources mentioned?yes
- Are the mentioned sources correct?yes

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
