### ISSUE TITLE
Feedback Request: SEC 4 Symmetric encryption

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#21]
**Feedback Request SEC 4 Symmetric encryption**
Permalink to file: [SEC 4 Symmetric encryption](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%203%20Security/SEC%204%20Symmetric%20encryption.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
Very clear, nice and detailed with complementing pictures. Could use a more detailed summary.

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? **Kind of, could be more extensive.**
- Is the summary written in own words? **Yes**
- Is there crucial information missing in the summary? **See above**
- Is the description clear enough? **See above**

**Key Terminology**
- Are there missing key terms? **No**
- Are the key terms explained well? **Yes**

**Sources**
- Are the sources mentioned? **Yes**
- Are the mentioned sources correct? **Yes**

**Excercise**
(Where applicable)
- Is the result correct? **Yes, but missing the analyse of why this method has shortcomings. Also a spelling error in the first sentence: examples**
- Are the experienced problems and solutions described well? **Yes**

**Comment by archana-sekarr** [comment]
Suitable illustrations have been attached to clearly understand the topic. As mentioned above, the summary could have been elaborated.
