### ISSUE TITLE
Feedback Request: SEC 8 Detection, response and analysis

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#25]
**Feedback Request SEC 8 Detection, response and analysis**
Permalink to file: [SEC 8 Detection, response and analysis](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%203%20Security/SEC%208%20Detection%2C%20response%20and%20analysis.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Good use of screenshots to explain different terminology
- All and all very good!

**Comment by QuincyTjia** [comment]
**Summary**
- Does the summary describe the subject matter fully? **Yes**
- Is the summary written in own words? **Yes**
- Is there crucial information missing in the summary? **No**
- Is the description clear enough? **Yes**

**Key Terminology**
- Are there missing key terms? **No**
- Are the key terms explained well? **Yes, very well**

**Sources**
- Are the sources mentioned? **Yes**
- Are the mentioned sources correct? **Yes**

**Excercise**
(Where applicable)
- Is the result correct? **Yes**
- Are the experienced problems and solutions described well? **Yes**

**Comment by archana-sekarr** [comment]
Key terminologies have been explained well and right use of pictures to explain the concept.
