### ISSUE TITLE
Feedback Request: Az 01 Azure Global Infrastructure

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#26]
**Feedback Request Az 01 Azure Global Infrastructure**
Permalink to file: [Az 01 Azure Global Infrastructure](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%204%20Cloud%20Fundamentals/AZ%201%20Azure%20Global%20Infrastructure.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Acron0815** [comment]
Summary

Does the summary describe the subject matter fully? ja
Is the summary written in own words? ?
Is there crucial information missing in the summary? nee
Is the description clear enough? ja

Key Terminology
Are there missing key terms? nee
Are the key terms explained well? ja
Sources

Are the sources mentioned? ja
Are the mentioned sources correct? ja
Excercise
(Where applicable)

Is the result correct? ja
Are the experienced problems and solutions described well? ja

**Comment by Tjomba1996** [comment]
Nothing to add. Looks very good!

**Comment by yismailmo** [comment]
Well structured and explained, and the last point about the costs, maybe you could've  explain a little bit more.
