### ISSUE TITLE
Feedback Request: AZ 3 Advantages of the cloud

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#28]
**Feedback Request: AZ 3 Advantages of the cloud
**
Permalink to file: [AZ 3 Advantages of the cloud](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%204%20Cloud%20Fundamentals/AZ%203%20Advantages%20of%20the%20cloud.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Explanation of consumption-model repeats itself
- Advantages explained well!

**Comment by yismailmo** [comment]
Nothing to add, and well done.
