### ISSUE TITLE
Feedback Request: Git Markdown

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#3]
**Feedback Request Git Markdown**
Permalink to file: [Git Markdonw](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/01_Fundamentals_1/Git%20Markdown.md)
Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by sasudi90** [comment]
- Vergeet niet de beschrijving onder de eerste heading te zetten en de exercise
- Een prachtig gedicht met markdown syntax en upload van afbeelding
