### ISSUE TITLE
Feedback Request: AZ 6 VM

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#31]
**Feedback Request AZ 6 VM**
Permalink to file: [AZ 6 VM](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%204%20Cloud%20Fundamentals/AZ%206%20Azure%20Virtual%20Machines.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Acron0815** [comment]
ummary

Does the summary describe the subject matter fully? ja
Is the summary written in own words? ?
Is there crucial information missing in the summary? nee
Is the description clear enough? ja

Key Terminology
Are there missing key terms? nee
Are the key terms explained well? ja
Sources

Are the sources mentioned? ja
Are the mentioned sources correct? ja
Excercise
(Where applicable)

Is the result correct? ja
Are the experienced problems and solutions described well? ja

**Comment by benbui797** [comment]
`The Service with which you can create VMs in Azure is (very appropriately) called Azure Virtual Machines. ` LOL

"You can optionally protect your VM with a NIC network security group. It is recommended to configure network security groups at the subnet level (and not at the instance level) where possible, but sometimes you need an allow/deny rule on a specific instance, so the option is there. In any case, you can arrange firewalls outside the instance, and you do not have to configure an extra firewall within the VM." 

This alinea confused me a little bit and had to re-read it before fully understanding it (and then I figured out it's the same as AWS hehe)

The results are all correct!
