### ISSUE TITLE
Feedback Request: AZ 7 Azure Disk Storage

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#32]
**Feedback Request AZ 7 Azure Disk Storage**
Permalink to file: [AZ 7 Azure Disk Storage](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%204%20Cloud%20Fundamentals/AZ%207%20Azure%20Disk%20Storage.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Missing key terms like: Snapshot, storage account.
- Could be more descriptive in results
