### ISSUE TITLE
Feedback Request: AZ 9 Shared Responsibility Model

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#34]
**Feedback Request AZ 9 Shared Responsibility Model**
Permalink to file: [AZ 9 Shared Responsibility Model](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%205%20Cloud%20Fundamentals/AZ%209%20Shared%20Responsibility%20Model.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
Looks good, the summary is nice and the pictures support the words and add clarity!
