### ISSUE TITLE
Feedback Request: AZ 10 Azure Virtual Network (VNet)

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#35]
**Feedback Request AZ 10 Azure Virtual Network (VNet)**
Permalink to file: [AZ 10 Azure Virtual Network (VNet)](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%205%20Cloud%20Fundamentals/AZ%2010%20Virtual%20Network%20(Vnet).md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by yismailmo** [comment]
good results , however not well structured  like (There are three ways to connect your network to an on-premises network: Point to Site VPNs: The Azure VNet is accessed with a VPN ) so maybe a space or create bullet points and overall the assignment is understood.
