### ISSUE TITLE
Feedback Request: AZ 11 Azure Load Balancer (ALB) & Auto Scaling

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#36]
**Feedback Request AZ 11 Azure Load Balancer (ALB) & Auto Scaling**
Permalink to file: [AZ 11 Azure Load Balancer (ALB) & Auto Scaling](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%205%20Cloud%20Fundamentals/AZ%2011%20ALB%2C%20Autoscaling.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by yismailmo** [comment]
very creative with your results and especially the command to test the load. Just missing a good structure of your document and resizing the load balancer photo in key terminology but other than that, well done with the assignment.

**Comment by benbui797** [comment]
Bonus points for the creative solution on Load Testing :)
