### ISSUE TITLE
Feedback Request: AZ 12 Well-Architected Framework

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#37]
**Feedback Request AZ 12 Well-Architected Framework**
Permalink to file: [AZ 12 Well-Architected Framework](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%205%20Cloud%20Fundamentals/AZ%2012%20Well%20Architected%20Framework.md#estimate-the-initial-cost)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Nicely structured, good layout!
- I miss the part where you explain what Services you can use to help achieve the design principles.
