### ISSUE TITLE
Feedback Request: AZ 13.1 App Service

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#38]
**Feedback Request AZ 13.1 App Service**
Permalink to file: [AZ 13.1 App Service](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%205%20Cloud%20Fundamentals/AZ%2013.1%20App%20Service%20.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by benbui797** [comment]
Very clear overview and I think it's a great idea to launch the test app as a practical exercise! I'll add it to mine as well hehe :)

**Comment by yismailmo** [comment]
Good to see that you've done the deployment of the test app as bonus.
