### ISSUE TITLE
Feedback Request: AZ 13.2 Content Delivery Network (CDN) 

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#39]
**Feedback Request AZ 13.2 Content Delivery Network (CDN) **
Permalink to file: [AZ 13.2 Content Delivery Network (CDN) ](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%205%20Cloud%20Fundamentals/AZ%2013.2%20Content%20Delivery%20Network%20(CDN)%20.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Good picture!
- Small thing, but put PoPs in key terms.
- Comparison is more of a summary of a different service. Maybe try to highlight pro's and cons
- Well explained, very clear!

**Comment by yismailmo** [comment]
well explained with the pictures, but maybe the CDN in a classic setting you can add the info to the first photo(without CDN).  All-in-all looks good.
