### ISSUE TITLE
Feedback Request: Linux 1 Setting Up

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#4]
**Feedback Request Linux 1 Setting Up**
Permalink to file: [Linux 1 Setting Up](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/02_Linux_1/Linux%201.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by sasudi90** [comment]
- Goede samenvatting
- Ik mis uitleg over wat een public key of VM is. Ook mis ik eventueel 'private key'
- Correct resultaat :D
