### ISSUE TITLE
Feedback Request: AZ 13.4 Azure Files

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#41]
**Feedback Request AZ 13.4 Azure Files**
Permalink to file: [AZ 13.4 Azure Files](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%205%20Cloud%20Fundamentals/AZ%2013.4%20Azure%20Files.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Little typo I guess in: How does azure files fit/replace azure files?
- What is a NAS device?
- typo: Better security than tradidional...
- Assignment well done!
- Awesome Comparison!

**Comment by abdeslamazhir** [comment]
> * Little typo I guess in: How does azure files fit/replace azure files?
> * What is a NAS device?
> * typo: Better security than tradidional...
> * Assignment well done!
> * Awesome Comparison!

Than you TOM, I will change it!

**Comment by yismailmo** [comment]
Looks good, well done
