### ISSUE TITLE
Feedback Request: AZ 13.5 Azure Database (+ managed instance) 

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#42]
**Feedback Request AZ 13.5 Azure Database (+ managed instance) **
Permalink to file: [AZ 13.5 Azure Database (+ managed instance) ](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%205%20Cloud%20Fundamentals/AZ%2013.5%20Azure%20Database%20(%2B%20managed%20instance)%20.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by yismailmo** [comment]
Good and maybe as bonus look how to link managed SQL to other resources. great job with the comparison.
