### ISSUE TITLE
Feedback Request: AZ 14 Containers

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#43]
**Feedback Request AZ 14 Containers**
Permalink to file: [AZ 14 Containers](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%206%20Cloud%20Fundamentals/14%20Containers.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
Very well done! All explanations are clear and correct!

**Comment by benbui797** [comment]
Looks good! The "Why" part is very clear, I like that you noted the different advantages and explained the how for each of them!

Amazon EC2 is our VM service, our container service is called AWS ECS ;)

**Comment by abdeslamazhir** [comment]
> Looks good! The "Why" part is very clear, I like that you noted the different advantages and explained the how for each of them!
> 
> Amazon EC2 is our VM service, our container service is called AWS ECS ;)
Thnx, modified it.

**Comment by yismailmo** [comment]
Good explanation, espacially i liked the cargo analogy with the containers.
