### ISSUE TITLE
Feedback Request: AZ 15 Azure Support Plans

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#44]
**Feedback Request AZ 15 Azure Support Plans**
Permalink to file: [AZ 15 Azure Support Plans](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%206%20Cloud%20Fundamentals/15%20Azure%20Support%20Plans.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Screenshot doesn't work
- Nice screenshots to show the portal!
- Good link for comparison, but try to explain it in the document as well, though that can be very minimal. Like the fact that azure has a free plan and AWS doesn't.

**Comment by yismailmo** [comment]
Clearly explained, but the last comparison "The main difference between Azure and AWS Service Plans is that THE first tier of the AWS plan is paid, and by Azure that one is free." But AWS has also free and premium (Developer, Business en Enterprise) and in Azure you'll also have to pay from developer to professional direct. So i think in Azure it's role based cost and in AWS is % of AWS usage.
