### ISSUE TITLE
Feedback Request: AZ 18 Azure Activity Log

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#47]
**Feedback Request AZ 18 Azure Activity Log**
Permalink to file: [AZ 18 Azure Activity Log](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%206%20Cloud%20Fundamentals/18%20Azure%20Activity%20Log.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Short explanation, well done!

**Comment by yismailmo** [comment]
nice summary and good to see you have the screenshot of the monitor.
