### ISSUE TITLE
Feedback Request: AZ 19 Azure Active Directory

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#48]
**Feedback Request AZ 19 Azure Active Directory**
Permalink to file: [AZ 19 Azure Active Directory](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%206%20Cloud%20Fundamentals/19%20Azure%20Active%20Directory.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by yismailmo** [comment]
Nice summary and I like that you've invited a user and you've also compared AD and Azure AD.

**Comment by Tjomba1996** [comment]
Very well explained, good exercise to show how it works!
