### ISSUE TITLE
Feedback Request: AZ 23 Event Grid, Queue Storage, Service Bus

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#52]
**Feedback Request AZ 23 Event Grid, Queue Storage, Service Bus**
Permalink to file: [AZ 23 Event Grid, Queue Storage, Service Bus](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/Week%206%20Cloud%20Fundamentals/23%20Event%20Grid%2C%20Queue%20Storage%2C%20Service%20Bus.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Tjomba1996** [comment]
- Good picture for service Bus
- Well done!
