### ISSUE TITLE
Feedback Request: Linux 4 Users and groups

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#7]
**Feedback Request Linux 4 Users and groups**
Permalink to file: [Linux 4 Users and groups](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/02_Linux_1/Linux%204.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by sasudi90** [comment]
- mis bij key terminology nog etc/passwd
- zou bij iedere image wat je showt kort omschrijven wat er te zien valt 
- je geeft aan moeite te hebben met deze assignment; breek dit in kleine stukken bij 'overcome challenges'. Wat waren de obstakels? Hoe ben je begonnen te zoeken?
