### ISSUE TITLE
Feedback Request:Linux 5 File permissions

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#8]
**Feedback Request Linux 5 File permissions**
Permalink to file: [Linux 5 File permissions](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/02_Linux_1/Linux%205.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by sasudi90** [comment]
- kort maar krachtige samenvatting
- mist bij key terms: u, g, o, chown
- mis de exercise
- experienced experience mag wel iets uitgebreider
- goed resultaat uiteraard
