### ISSUE TITLE
Feedback Request: Linux 6 Processes

### ISSUE THREAD

**Issue by abdeslamazhir** [TechGrounds-Cloud8/cloud8-abdeslamazhir#9]
**Feedback Request Linux 6 Processes**
Permalink to file: [Linux 6 Processes](https://github.com/TechGrounds-Cloud8/cloud8-abdeslamazhir/blob/main/02_Linux_1/Linux%206.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by sasudi90** [comment]
Loop alles nog even na als je tijd hebt. :) Samenvatting, exercises, begeleidend verhaal rondom subopdrachten etc etc
